name: Release and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '23'

    - name: Install Dependencies
      run: npm ci

    - name: Build App
      run: npm run build

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy via rsync
      env:
        RSYNC_RSH: 'ssh -o StrictHostKeyChecking=no'
      run: |
        rsync -avz --delete public/ github-actions@openpsg.com:/var/www/openpsg.com/viewer/
